/* eslint-env node */
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2022,
    sourceType: "module",
    project: ["./tsconfig.json"],
  },
  plugins: ["@typescript-eslint", "functional"],
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/strict-type-checked",
    "plugin:functional/strict",
    "prettier",
  ],
  rules: {
    "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    "functional/no-expression-statements": ["error", { ignoreVoid: true }],
    "functional/no-throw-statements": ["error", { allowInAsyncFunctions: true }],
    "functional/no-return-void": "off",
    "functional/prefer-immutable-types": "off",
    "functional/type-declaration-immutability": "off",
    "functional/no-mixed-types": "off",
  },
  overrides: [
    {
      files: ["**/*.test.ts"],
      extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "prettier"],
      rules: {
        "functional/functional-parameters": "off",
        "functional/immutable-data": "off",
        "functional/no-classes": "off",
        "functional/no-conditional-statements": "off",
        "functional/no-expression-statements": "off",
        "functional/no-let": "off",
        "functional/no-loop-statements": "off",
        "functional/no-return-void": "off",
        "functional/no-this-expressions": "off",
        "functional/no-throw-statements": "off",
        "functional/no-mixed-types": "off",
        "functional/prefer-immutable-types": "off",
        "functional/prefer-property-signatures": "off",
        "functional/prefer-tacit": "off",
        "functional/readonly-type": "off",
        "functional/type-declaration-immutability": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-non-null-assertion": "off",
        "@typescript-eslint/no-unsafe-assignment": "off",
        "@typescript-eslint/no-unsafe-member-access": "off",
      },
    },
  ],
};
