// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./interfaces/ILemmaProofSettlement.sol";

/**
 * @title LemmaProofSettlement
 * @notice Verifies a ZK proof via a caller-specified verifier contract
 *         and records the result on-chain.
 *
 *         Whitepaper §3.1 Layer 1 — extends the on-chain provenance layer
 *         to include proof verification results alongside document registration.
 *
 *         The verifier address is passed at call time (not stored in a registry)
 *         because the same algorithm (e.g. groth16-bn254-snarkjs) produces
 *         a unique verifier contract per circuit — snarkjs embeds the
 *         circuit-specific verification key into the generated Solidity.
 *
 *         Access is restricted to authorized callers (LemmaRelay, Workers wallet, etc.).
 */
contract LemmaProofSettlement is ILemmaProofSettlement {
  /* ── Types ───────────────────────────────────────────────────── */

  struct ProofRecord {
    bytes32 docHash;
    bytes32 circuitIdHash;
    address verifier;
    bool    valid;
    uint256 settledAt;
  }

  /* ── State ───────────────────────────────────────────────────── */

  address public owner;
  mapping(address => bool) public authorizedCallers;
  mapping(bytes32 => ProofRecord) public records;

  /* ── Events ──────────────────────────────────────────────────── */

  event ProofSettled(
    bytes32 indexed verificationId,
    bytes32 indexed docHash,
    bytes32 indexed circuitIdHash,
    address verifier,
    bool    valid
  );

  event AuthorizedCallerAdded(address indexed caller);
  event AuthorizedCallerRemoved(address indexed caller);

  /* ── Errors ──────────────────────────────────────────────────── */

  error NotOwner();
  error Unauthorized();
  error InvalidVerifier();
  error AlreadySettled(bytes32 verificationId);
  error InvalidAddress();
  error AlreadyAuthorized();
  error NotAuthorized();
  error CannotRemoveOwner();

  /* ── Modifiers ───────────────────────────────────────────────── */

  modifier onlyOwner() {
    if (msg.sender != owner) revert NotOwner();
    _;
  }

  modifier onlyAuthorized() {
    if (!authorizedCallers[msg.sender]) revert Unauthorized();
    _;
  }

  /* ── Constructor ─────────────────────────────────────────────── */

  constructor() {
    owner = msg.sender;
    authorizedCallers[msg.sender] = true;
    emit AuthorizedCallerAdded(msg.sender);
  }

  /* ── Admin ───────────────────────────────────────────────────── */

  function addAuthorizedCaller(address caller) external onlyOwner {
    if (caller == address(0)) revert InvalidAddress();
    if (authorizedCallers[caller]) revert AlreadyAuthorized();
    authorizedCallers[caller] = true;
    emit AuthorizedCallerAdded(caller);
  }

  function removeAuthorizedCaller(address caller) external onlyOwner {
    if (!authorizedCallers[caller]) revert NotAuthorized();
    if (caller == owner) revert CannotRemoveOwner();
    authorizedCallers[caller] = false;
    emit AuthorizedCallerRemoved(caller);
  }

  function transferOwnership(address newOwner) external onlyOwner {
    if (newOwner == address(0)) revert InvalidAddress();
    owner = newOwner;
  }

  /* ── Core ────────────────────────────────────────────────────── */

  /// @inheritdoc ILemmaProofSettlement
  function settle(
    bytes32 verificationId,
    bytes32 docHash,
    bytes32 circuitIdHash,
    address verifier,
    uint256[2] calldata pA,
    uint256[2][2] calldata pB,
    uint256[2] calldata pC,
    uint256[] calldata pubSignals
  ) external onlyAuthorized returns (bool valid) {
    if (verifier == address(0)) revert InvalidVerifier();
    if (records[verificationId].settledAt != 0) revert AlreadySettled(verificationId);

    // staticcall: verifier is a pure/view contract generated by snarkjs.
    // staticcall prevents any state mutation on the verifier side.
    (bool success, bytes memory ret) = verifier.staticcall(
      abi.encodeWithSignature(
        "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[])",
        pA, pB, pC, pubSignals
      )
    );

    valid = success && ret.length >= 32 && abi.decode(ret, (bool));

    records[verificationId] = ProofRecord({
      docHash:       docHash,
      circuitIdHash: circuitIdHash,
      verifier:      verifier,
      valid:         valid,
      settledAt:     block.timestamp
    });

    emit ProofSettled(verificationId, docHash, circuitIdHash, verifier, valid);
  }

  /* ── Views ───────────────────────────────────────────────────── */

  /// @inheritdoc ILemmaProofSettlement
  function isSettled(bytes32 verificationId) external view returns (bool) {
    return records[verificationId].settledAt != 0;
  }

  function getRecord(bytes32 verificationId) external view returns (ProofRecord memory) {
    return records[verificationId];
  }
}
